version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_new_database
    ports:
      - "3306:3306"
    networks:
      - mysql-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-container
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - mysql-network
    restart: always

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
